//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.08 at 08:07:38 PM CEST 
//


package rs.ac.uns.ftn.informatika.odgovorizvod;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.informatika.odgovorizvod package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.informatika.odgovorizvod
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PreuzetOdgovor }
     * 
     */
    public PreuzetOdgovor createPreuzetOdgovor() {
        return new PreuzetOdgovor();
    }

    /**
     * Create an instance of {@link PresekStavki }
     * 
     */
    public PresekStavki createPresekStavki() {
        return new PresekStavki();
    }

    /**
     * Create an instance of {@link PoslatOdgovor }
     * 
     */
    public PoslatOdgovor createPoslatOdgovor() {
        return new PoslatOdgovor();
    }

    /**
     * Create an instance of {@link OdgovorIzvod }
     * 
     */
    public OdgovorIzvod createOdgovorIzvod() {
        return new OdgovorIzvod();
    }

}
