//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.08 at 08:07:38 PM CEST 
//


package rs.ac.uns.ftn.informatika.korisnickinalog;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Korisnicki_nalog complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Korisnicki_nalog">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Port_korisnika">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Port_banke">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Racun">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="18"/>
 *               &lt;minLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Naziv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Pib">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="11"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Stanje_na_racunu" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Rezervisana_suma" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Korisnicki_nalog", propOrder = {
    "portKorisnika",
    "portBanke",
    "racun",
    "naziv",
    "pib",
    "stanjeNaRacunu",
    "rezervisanaSuma"
})
public class KorisnickiNalog {

    @XmlElement(name = "Port_korisnika", required = true)
    protected String portKorisnika;
    @XmlElement(name = "Port_banke", required = true)
    protected String portBanke;
    @XmlElement(name = "Racun", required = true)
    protected String racun;
    @XmlElement(name = "Naziv", required = true)
    protected String naziv;
    @XmlElement(name = "Pib", required = true)
    protected String pib;
    @XmlElement(name = "Stanje_na_racunu")
    protected double stanjeNaRacunu;
    @XmlElement(name = "Rezervisana_suma")
    protected double rezervisanaSuma;

    /**
     * Gets the value of the portKorisnika property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortKorisnika() {
        return portKorisnika;
    }

    /**
     * Sets the value of the portKorisnika property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortKorisnika(String value) {
        this.portKorisnika = value;
    }

    /**
     * Gets the value of the portBanke property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortBanke() {
        return portBanke;
    }

    /**
     * Sets the value of the portBanke property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortBanke(String value) {
        this.portBanke = value;
    }

    /**
     * Gets the value of the racun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRacun() {
        return racun;
    }

    /**
     * Sets the value of the racun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRacun(String value) {
        this.racun = value;
    }

    /**
     * Gets the value of the naziv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaziv() {
        return naziv;
    }

    /**
     * Sets the value of the naziv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaziv(String value) {
        this.naziv = value;
    }

    /**
     * Gets the value of the pib property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPib() {
        return pib;
    }

    /**
     * Sets the value of the pib property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPib(String value) {
        this.pib = value;
    }

    /**
     * Gets the value of the stanjeNaRacunu property.
     * 
     */
    public double getStanjeNaRacunu() {
        return stanjeNaRacunu;
    }

    /**
     * Sets the value of the stanjeNaRacunu property.
     * 
     */
    public void setStanjeNaRacunu(double value) {
        this.stanjeNaRacunu = value;
    }

    /**
     * Gets the value of the rezervisanaSuma property.
     * 
     */
    public double getRezervisanaSuma() {
        return rezervisanaSuma;
    }

    /**
     * Sets the value of the rezervisanaSuma property.
     * 
     */
    public void setRezervisanaSuma(double value) {
        this.rezervisanaSuma = value;
    }

}
