//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.09 at 05:47:43 PM CEST 
//


package rs.ac.uns.ftn.informatika.zahtevizvod;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Izvod_zahtev" type="{http://www.informatika.ftn.uns.ac.rs/zahtevIzvod}Zahtev_izvod"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "izvodZahtev"
})
@XmlRootElement(name = "Poslat_zahtev")
public class PoslatZahtev {

    @XmlElement(name = "Izvod_zahtev", required = true)
    protected ZahtevIzvod izvodZahtev;

    /**
     * Gets the value of the izvodZahtev property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevIzvod }
     *     
     */
    public ZahtevIzvod getIzvodZahtev() {
        return izvodZahtev;
    }

    /**
     * Sets the value of the izvodZahtev property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevIzvod }
     *     
     */
    public void setIzvodZahtev(ZahtevIzvod value) {
        this.izvodZahtev = value;
    }

}
