//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.09 at 05:48:52 PM CEST 
//


package rs.ac.uns.ftn.informatika.mt910;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MT910Odg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mt910Odg"
})
@XmlRootElement(name = "Odgovor910")
public class Odgovor910 {

    @XmlElement(name = "MT910Odg", required = true)
    protected String mt910Odg;

    /**
     * Gets the value of the mt910Odg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMT910Odg() {
        return mt910Odg;
    }

    /**
     * Sets the value of the mt910Odg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMT910Odg(String value) {
        this.mt910Odg = value;
    }

}
