//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.09 at 05:48:13 PM CEST 
//


package rs.ac.uns.ftn.informatika.mt900;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MT900Odg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mt900Odg"
})
@XmlRootElement(name = "Odgovor900")
public class Odgovor900 {

    @XmlElement(name = "MT900Odg", required = true)
    protected String mt900Odg;

    /**
     * Gets the value of the mt900Odg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMT900Odg() {
        return mt900Odg;
    }

    /**
     * Sets the value of the mt900Odg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMT900Odg(String value) {
        this.mt900Odg = value;
    }

}
